### ISSUE TITLE
Update cockroach sql.conn.max_read_buffer_message_size 

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_graphql#130]
Clean sync from 0 with version 2.11.2 (current devnet) results in:

```
{"level":2,"time":1692358200617,"ns":"sqd:substrate-ingest","msg":"connected to postgres://db:26257/defaultdb"}
{"level":2,"time":1692358200618,"ns":"sqd:substrate-ingest","msg":"Loading migrations from: /squid/substrate/substrate-ingest/migrations"}
{"level":2,"time":1692358200619,"ns":"sqd:substrate-ingest","msg":"Found migration files: 001-initial.sql,002-ethereum-transaction.sql,003-add-evm-log.sql"}
{"level":2,"time":1692358200628,"ns":"sqd:substrate-ingest","msg":"Acquiring advisory lock..."}
{"level":2,"time":1692358200632,"ns":"sqd:substrate-ingest","msg":"... acquired advisory lock"}
{"level":2,"time":1692358200632,"ns":"sqd:substrate-ingest","msg":"Starting migrations"}
{"level":2,"time":1692358200651,"ns":"sqd:substrate-ingest","msg":"Migrations table with name 'migrations' exists, filtering not applied migrations."}
{"level":2,"time":1692358200655,"ns":"sqd:substrate-ingest","msg":"No migrations applied"}
{"level":2,"time":1692358200655,"ns":"sqd:substrate-ingest","msg":"Finished migrations"}
{"level":2,"time":1692358200655,"ns":"sqd:substrate-ingest","msg":"Releasing advisory lock..."}
{"level":2,"time":1692358200657,"ns":"sqd:substrate-ingest","msg":"... released advisory lock"}
{"level":2,"time":1692358200668,"ns":"sqd:substrate-ingest","msg":"continuing from block 5953460"}
{"level":2,"time":1692358200691,"ns":"sqd:substrate-ingest","msg":"prometheus server is listening on port 9090"}
{"level":2,"time":1692358200707,"ns":"sqd:substrate-ingest","msg":"chain height is 7179758"}
{"level":5,"time":1692358202943,"ns":"sqd:substrate-ingest","err":{"length":249,"name":"error","severity":"ERROR","code":"08P01","hint":"the maximum message size can be configured using the sql.conn.max_read_buffer_message_size cluster setting","file":"encoding.go","line":"286","routine":"NewProtocolViolationErrorf","stack":"error: message size 18 MiB bigger than maximum allowed message size 16 MiB\n    at Parser.parseErrorMessage (/squid/common/temp/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/squid/common/temp/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/squid/common/temp/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/squid/common/temp/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"}}
```

Using 2.11.2 on testnet works well though, this issue only appears on devnet.
Deploy happens via docker-compose, using the compose file from the repo but only mapping /cockroach/cockroach-data to /srv/indexer/. This used to work flawlessly (as it does on testnet currently).

```
version: "3.4"

services:
  db:
    image: cockroachdb/cockroach:v22.2.2
    restart: always
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - /srv/indexer/:/cockroach/cockroach-data

  ingest:
    depends_on:
      - db
    restart: on-failure
    image: subsquid/substrate-ingest:1
    volumes:
      - "./typesBundle.json:/configs/typesBundle.json"
    command:
      [
        "-e",
        "${WS_ENDPOINT}",
        "-c",
        "20",
        "--out",
        "postgres://root@db:26257/defaultdb",
        "--types-bundle",
        "/configs/typesBundle.json"
      ]

  gateway:
    depends_on:
      - db
    image: subsquid/substrate-gateway:2.5.0
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: [ "--database-url", "postgres://root@db:26257/defaultdb" ]
    ports:
      - "8888:8000"

  explorer:
    image: subsquid/substrate-explorer:firesquid
    environment:
      DB_TYPE: cockroach
      DB_HOST: db
      DB_PORT: "26257"
      DB_NAME: "defaultdb"
      DB_USER: "root"
    ports:
      - "4444:3000"
```

**Comment by LeeSmet** [comment]
https://github.com/cockroachdb/cockroach/issues/63782#issuecomment-825122595

**Comment by coesensbert** [comment]
resolved by:
```
docker exec -it indexer_db_1 /bin/bash
./cockroach sql --insecure
SET CLUSTER SETTING sql.conn.max_read_buffer_message_size = '32MiB';
```

**Comment by coesensbert** [comment]
This issue is still present. It has been a while since a new indexer version was released, so we resolved it with the above cluster setting on the running indexers. On deploying a new indexer (like with docker-compose) we encounter the `sql.conn.max_read_buffer_message_size `error. This is set to 16 MiB by default. By setting this to 32 MiB the error was resolved but it would be good if dev could confirm this cockroachdb change is ok or not.

If ok, could this cluster setting be set by default for the helm chart and docker-compose file?

**Comment by sameh-farouk** [comment]
> It would be good if dev could confirm this cockroachdb change is ok or not.
 
Nothing wrong with setting it to 32 MiB.

> If ok, could this cluster setting be set by default for the helm chart and docker-compose file?

Sure, will put this on my todo list

**Comment by sameh-farouk** [comment]
@coesensbert can you verify that this now is solved

**Comment by sameh-farouk** [comment]
Just to clarify, I have updated the indexer docker compose and now accompany with setup_db.sh you can spin it with no issue.

**Comment by coesensbert** [comment]
Great, will test a full sync from 0 for the indexer for all nets. This can take a while. Thanks.

**Comment by coesensbert** [comment]
added to the grid backend compose stacks and tested https://github.com/threefoldtech/grid_deployment/issues/54
looks good, thx!

Doing a full indexer sync from 0 for all nets since this was the original issue: https://github.com/threefoldtech/tf_operations/issues/2570
