### ISSUE TITLE
Bug: node-fetch used by squid-sdk/util/util-internal-http-client is not compatible with node 20

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfchain_graphql#183]
This error was noticed, but it seems not critical (Affecting the log module only), and the processor is functioning without noticeable issues.

```
{"ns":"sys","time":1717715452573,"level":4,"msg":"Failed to serialize log record from sqd:processor:archive-request","err":{"stack":"TypeError [ERR_INVALID_THIS]: Value of \"this\" must be of type URLSearchParams\n    at get size (node:internal/url:459:13)\n    at Reflect.get (<anonymous>)\n    at Object.get (file:///squid/node_modules/@subsquid/util-internal-http-client/node_modules/node-fetch/src/headers.js:143:22)\n    at toJsonObject (/squid/node_modules/@subsquid/util-internal-json/lib/json.js:63:33)\n    at toJSON (/squid/node_modules/@subsquid/util-internal-json/lib/json.js:46:24)\n    at toJsonObject (/squid/node_modules/@subsquid/util-internal-json/lib/json.js:63:23)\n    at toJSON (/squid/node_modules/@subsquid/util-internal-json/lib/json.js:46:24)\n    at stringify (/squid/node_modules/@subsquid/logger/lib/sinks/json.js:12:52)\n    at Logger.jsonLinesStderrSink [as sink] (/squid/node_modules/@subsquid/logger/lib/sinks/json.js:7:26)\n    at Logger.write (/squid/node_modules/@subsquid/logger/lib/logger.js:56:14)"}}
```

The original issue seems to be thrown by `node-fetch`. squid-sdk firesquid release uses a version that is not compatible with node 20. firesquid uses node 16.

We recently tried to use node 20 which triggered this issue, so reverting to node 18 should make it work.

**Comment by sameh-farouk** [comment]
Current state

  - node-fetch: 3.3.2 (latest in the 3.x series — no fix available, last published Jul 2023, project appears unmaintained)
  - @subsquid/util-internal-http-client: 0.1.0 (depends on node-fetch@^3.3.0)
  - @subsquid/substrate-processor: 2.4.1 (FireSquid generation — targets Node 16)
  - Dockerfile: node:20-alpine
  - Even the latest Subsquid SDK (@subsquid/http-client@1.8.0, ArrowSquid) still depends on node-fetch@^3.3.2 — so upgrading the SDK alone doesn't fix this

Impact

Non-critical. The error only affects log serialization — when the processor tries to log an HTTP request at debug level, the serialization fails. The processor itself continues functioning. No data loss or indexing issues.

The previous draft PR https://github.com/threefoldtech/tfchain_graphql/pull/184 downgrading to Node 18 is now moot since 18 is EOL)

**Recemendation**: keep Node 20, the error is harmless.
