### ISSUE TITLE
[mainnet] processor crashes

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_graphql#195]
dashboard.grid.tf
```
{"level":2,"time":1728447617618,"ns":"sqd:processor","msg":"14594904 / 14594904, rate: 0 blocks/sec, mapping: 1 blocks/sec, 11 items/sec, ingest: 62 blocks/sec, eta: 0s"}
{"level":2,"time":1728447622728,"ns":"sqd:processor","msg":"14594905 / 14594905, rate: 0 blocks/sec, mapping: 1 blocks/sec, 12 items/sec, ingest: 53 blocks/sec, eta: 0s"}
{"level":2,"time":1728447627257,"ns":"sqd:processor","msg":"14594906 / 14594906, rate: 0 blocks/sec, mapping: 1 blocks/sec, 12 items/sec, ingest: 54 blocks/sec, eta: 0s"}
{"level":2,"time":1728447637704,"ns":"sqd:processor","msg":"14594907 / 14594907, rate: 0 blocks/sec, mapping: 1 blocks/sec, 13 items/sec, ingest: 53 blocks/sec, eta: 0s"}
{"level":2,"time":1728447645523,"ns":"sqd:processor","msg":"14594908 / 14594908, rate: 0 blocks/sec, mapping: 1 blocks/sec, 11 items/sec, ingest: 54 blocks/sec, eta: 0s"}
{"level":2,"time":1728447650009,"ns":"sqd:processor","msg":"14594909 / 14594909, rate: 0 blocks/sec, mapping: 1 blocks/sec, 8 items/sec, ingest: 54 blocks/sec, eta: 0s"}
{"level":2,"time":1728447652335,"ns":"sqd:processor","msg":"14594910 / 14594910, rate: 0 blocks/sec, mapping: 1 blocks/sec, 9 items/sec, ingest: 69 blocks/sec, eta: 0s"}
{"level":2,"time":1728447657349,"ns":"sqd:processor","msg":"14594911 / 14594911, rate: 0 blocks/sec, mapping: 1 blocks/sec, 9 items/sec, ingest: 67 blocks/sec, eta: 0s"}
{"level":2,"time":1728447670716,"ns":"sqd:processor","msg":"14594912 / 14594912, rate: 0 blocks/sec, mapping: 0 blocks/sec, 8 items/sec, ingest: 68 blocks/sec, eta: 0s"}
{"level":2,"time":1728447672587,"ns":"sqd:processor","msg":"14594913 / 14594913, rate: 0 blocks/sec, mapping: 1 blocks/sec, 10 items/sec, ingest: 69 blocks/sec, eta: 0s"}
{"level":2,"time":1728447680099,"ns":"sqd:processor","msg":"14594914 / 14594914, rate: 0 blocks/sec, mapping: 1 blocks/sec, 10 items/sec, ingest: 67 blocks/sec, eta: 0s"}
{"level":2,"time":1728447682577,"ns":"sqd:processor","msg":"14594915 / 14594915, rate: 0 blocks/sec, mapping: 1 blocks/sec, 10 items/sec, ingest: 69 blocks/sec, eta: 0s"}
{"level":2,"time":1728447687438,"ns":"sqd:processor","msg":"14594916 / 14594916, rate: 0 blocks/sec, mapping: 1 blocks/sec, 10 items/sec, ingest: 70 blocks/sec, eta: 0s"}
{"level":2,"time":1728447757423,"ns":"sqd:processor","msg":"14594917 / 14594919, rate: 0 blocks/sec, mapping: 0 blocks/sec, 8 items/sec, ingest: 41 blocks/sec, eta: 14s"}
{"level":2,"time":1728447757832,"ns":"sqd:processor","msg":"14594918 / 14594927, rate: 0 blocks/sec, mapping: 0 blocks/sec, 8 items/sec, ingest: 42 blocks/sec, eta: 2m"}
{"level":2,"time":1728447758410,"ns":"sqd:processor","msg":"14594919 / 14594927, rate: 0 blocks/sec, mapping: 0 blocks/sec, 8 items/sec, ingest: 42 blocks/sec, eta: 56s"}
{"level":2,"time":1728447778220,"ns":"sqd:processor","msg":"14594927 / 14594929, rate: 0 blocks/sec, mapping: 0 blocks/sec, 8 items/sec, ingest: 80 blocks/sec, eta: 13s"}
{"level":2,"time":1728447794303,"ns":"sqd:processor","msg":"14594928 / 14594931, rate: 0 blocks/sec, mapping: 0 blocks/sec, 8 items/sec, ingest: 73 blocks/sec, eta: 20s"}
{"level":2,"time":1728447812762,"ns":"sqd:processor","msg":"14594929 / 14594934, rate: 0 blocks/sec, mapping: 0 blocks/sec, 7 items/sec, ingest: 92 blocks/sec, eta: 34s"}
{"level":2,"time":1728447849778,"ns":"sqd:processor","msg":"14594931 / 14594937, rate: 0 blocks/sec, mapping: 0 blocks/sec, 7 items/sec, ingest: 82 blocks/sec, eta: 43s"}
{"level":2,"time":1728447854505,"ns":"sqd:processor","msg":"14594934 / 14594943, rate: 0 blocks/sec, mapping: 0 blocks/sec, 7 items/sec, ingest: 92 blocks/sec, eta: 2m"}
{"level":2,"time":1728447856861,"ns":"sqd:processor","msg":"14594937 / 14594944, rate: 0 blocks/sec, mapping: 0 blocks/sec, 6 items/sec, ingest: 68 blocks/sec, eta: 46s"}
{"level":2,"time":1728447875187,"ns":"sqd:processor","msg":"14594943 / 14594945, rate: 0 blocks/sec, mapping: 0 blocks/sec, 7 items/sec, ingest: 93 blocks/sec, eta: 13s"}
{"level":2,"time":1728447875942,"ns":"sqd:processor","msg":"14594944 / 14594947, rate: 0 blocks/sec, mapping: 0 blocks/sec, 8 items/sec, ingest: 97 blocks/sec, eta: 19s"}
{"level":2,"time":1728447876528,"ns":"sqd:processor","msg":"14594945 / 14594947, rate: 0 blocks/sec, mapping: 1 blocks/sec, 10 items/sec, ingest: 107 blocks/sec, eta: 12s"}
{"level":2,"time":1728447877611,"ns":"sqd:processor","msg":"14594947 / 14594947, rate: 0 blocks/sec, mapping: 1 blocks/sec, 11 items/sec, ingest: 96 blocks/sec, eta: 0s"}
{"level":2,"time":1728447881686,"ns":"sqd:processor","msg":"14594948 / 14594948, rate: 0 blocks/sec, mapping: 1 blocks/sec, 11 items/sec, ingest: 84 blocks/sec, eta: 0s"}
{"level":2,"time":1728447886722,"ns":"sqd:processor","msg":"14594949 / 14594949, rate: 0 blocks/sec, mapping: 2 blocks/sec, 15 items/sec, ingest: 54 blocks/sec, eta: 0s"}
{"level":5,"time":1728447956571,"ns":"sqd:processor","err":{"query":"INSERT INTO \"node_contract\"(\"id\", \"grid_version\", \"contract_id\", \"twin_id\", \"node_id\", \"deployment_data\", \"deployment_hash\", \"number_of_public_i_ps\", \"state\", \"created_at\", \"solution_provider_id\", \"resources_used_id\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, DEFAULT) ON CONFLICT ( \"id\" ) DO UPDATE SET \"id\" = EXCLUDED.\"id\", \"grid_version\" = EXCLUDED.\"grid_version\", \"contract_id\" = EXCLUDED.\"contract_id\", \"twin_id\" = EXCLUDED.\"twin_id\", \"node_id\" = EXCLUDED.\"node_id\", \"deployment_data\" = EXCLUDED.\"deployment_data\", \"deployment_hash\" = EXCLUDED.\"deployment_hash\", \"number_of_public_i_ps\" = EXCLUDED.\"number_of_public_i_ps\", \"state\" = EXCLUDED.\"state\", \"created_at\" = EXCLUDED.\"created_at\", \"solution_provider_id\" = EXCLUDED.\"solution_provider_id\"","parameters":["0014594950-000837-077da",4,"686025",10972,730,"{\"version\":3,\"type\":\"vm\",\"name\":\"example_c1\",\"projectName\":\"vm/group_c\"}","1d188e89b23f4c17ab49c8eef7b68bca",0,"Created","1728447876",0],"driverError":{"length":180,"name":"error","severity":"ERROR","code":"P0001","where":"PL/pgSQL function reflect_node_contract_changes() line 42 at RAISE","file":"pl_exec.c","line":"3910","routine":"exec_stmt_raise","stack":"error: failed calc node_contracts_count deadlock detected\n    at /squid/node_modules/pg/lib/client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)\n    at async InsertQueryBuilder.execute (/squid/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)\n    at async Store.upsert (/squid/node_modules/@subsquid/typeorm-store/lib/store.js:34:13)\n    at async contractCreated (/squid/lib/mappings/contracts.js:106:9)\n    at async /squid/lib/processor.js:138:13\n    at async TypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    at async TypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    at async Runner.process (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:117:17)"},"length":180,"severity":"ERROR","code":"P0001","where":"PL/pgSQL function reflect_node_contract_changes() line 42 at RAISE","file":"pl_exec.c","line":"3910","routine":"exec_stmt_raise","stack":"QueryFailedError: failed calc node_contracts_count deadlock detected\n    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InsertQueryBuilder.execute (/squid/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)\n    at async Store.upsert (/squid/node_modules/@subsquid/typeorm-store/lib/store.js:34:13)\n    at async contractCreated (/squid/lib/mappings/contracts.js:106:9)\n    at async /squid/lib/processor.js:138:13\n    at async TypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    at async TypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    at async Runner.process (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:117:17)"}}
error Command failed with exit code 1.
```

https://[dashboard.fin.grid.tf](https://dashboard.fin.grid.tf/)/
```
{"level":2,"time":1724901988152,"ns":"sqd:processor","msg":"14004551 / 14004551, rate: 0 blocks/sec, mapping: 3 blocks/sec, 31 items/sec, ingest: 51 blocks/sec, eta: 0s"}
{"level":2,"time":1724901993183,"ns":"sqd:processor","msg":"14004552 / 14004552, rate: 0 blocks/sec, mapping: 3 blocks/sec, 32 items/sec, ingest: 53 blocks/sec, eta: 0s"}
{"level":2,"time":1724902003199,"ns":"sqd:processor","msg":"14004553 / 14004553, rate: 0 blocks/sec, mapping: 3 blocks/sec, 24 items/sec, ingest: 54 blocks/sec, eta: 0s"}
{"level":2,"time":1724902008226,"ns":"sqd:processor","msg":"14004554 / 14004554, rate: 0 blocks/sec, mapping: 3 blocks/sec, 25 items/sec, ingest: 54 blocks/sec, eta: 0s"}
{"level":2,"time":1724902013252,"ns":"sqd:processor","msg":"14004555 / 14004555, rate: 0 blocks/sec, mapping: 3 blocks/sec, 25 items/sec, ingest: 55 blocks/sec, eta: 0s"}
{"level":2,"time":1724902018264,"ns":"sqd:processor","msg":"14004556 / 14004556, rate: 0 blocks/sec, mapping: 3 blocks/sec, 25 items/sec, ingest: 56 blocks/sec, eta: 0s"}
{"level":2,"time":1724902023717,"ns":"sqd:processor","msg":"14004557 / 14004557, rate: 0 blocks/sec, mapping: 2 blocks/sec, 25 items/sec, ingest: 53 blocks/sec, eta: 0s"}
{"level":2,"time":1724902033467,"ns":"sqd:processor","msg":"14004558 / 14004558, rate: 0 blocks/sec, mapping: 2 blocks/sec, 28 items/sec, ingest: 51 blocks/sec, eta: 0s"}
{"level":2,"time":1724902038496,"ns":"sqd:processor","msg":"14004559 / 14004559, rate: 0 blocks/sec, mapping: 2 blocks/sec, 24 items/sec, ingest: 53 blocks/sec, eta: 0s"}
{"level":2,"time":1724902043393,"ns":"sqd:processor","msg":"14004560 / 14004560, rate: 0 blocks/sec, mapping: 2 blocks/sec, 23 items/sec, ingest: 52 blocks/sec, eta: 0s"}
{"level":2,"time":1724902048518,"ns":"sqd:processor","msg":"14004561 / 14004561, rate: 0 blocks/sec, mapping: 2 blocks/sec, 23 items/sec, ingest: 51 blocks/sec, eta: 0s"}
{"level":2,"time":1724902053617,"ns":"sqd:processor","msg":"14004562 / 14004562, rate: 0 blocks/sec, mapping: 2 blocks/sec, 24 items/sec, ingest: 55 blocks/sec, eta: 0s"}
{"level":2,"time":1724902063461,"ns":"sqd:processor","msg":"14004563 / 14004563, rate: 0 blocks/sec, mapping: 2 blocks/sec, 22 items/sec, ingest: 57 blocks/sec, eta: 0s"}
{"level":2,"time":1724902068568,"ns":"sqd:processor","msg":"14004564 / 14004564, rate: 0 blocks/sec, mapping: 2 blocks/sec, 23 items/sec, ingest: 54 blocks/sec, eta: 0s"}
{"level":2,"time":1724902073531,"ns":"sqd:processor","msg":"14004565 / 14004565, rate: 0 blocks/sec, mapping: 2 blocks/sec, 26 items/sec, ingest: 53 blocks/sec, eta: 0s"}
{"level":2,"time":1724902078542,"ns":"sqd:processor","msg":"14004566 / 14004566, rate: 0 blocks/sec, mapping: 3 blocks/sec, 28 items/sec, ingest: 55 blocks/sec, eta: 0s"}
{"level":2,"time":1724902083584,"ns":"sqd:processor","msg":"14004567 / 14004567, rate: 0 blocks/sec, mapping: 3 blocks/sec, 34 items/sec, ingest: 51 blocks/sec, eta: 0s"}
{"level":2,"time":1724902093629,"ns":"sqd:processor","msg":"14004568 / 14004568, rate: 0 blocks/sec, mapping: 3 blocks/sec, 34 items/sec, ingest: 52 blocks/sec, eta: 0s"}
{"level":5,"time":1724902098908,"ns":"sqd:processor","err":{"query":"INSERT INTO \"node_contract\"(\"id\", \"grid_version\", \"contract_id\", \"twin_id\", \"node_id\", \"deployment_data\", \"deployment_hash\", \"number_of_public_i_ps\", \"state\", \"created_at\", \"solution_provider_id\", \"resources_used_id\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, DEFAULT) ON CONFLICT ( \"id\" ) DO UPDATE SET \"id\" = EXCLUDED.\"id\", \"grid_version\" = EXCLUDED.\"grid_version\", \"contract_id\" = EXCLUDED.\"contract_id\", \"twin_id\" = EXCLUDED.\"twin_id\", \"node_id\" = EXCLUDED.\"node_id\", \"deployment_data\" = EXCLUDED.\"deployment_data\", \"deployment_hash\" = EXCLUDED.\"deployment_hash\", \"number_of_public_i_ps\" = EXCLUDED.\"number_of_public_i_ps\", \"state\" = EXCLUDED.\"state\", \"created_at\" = EXCLUDED.\"created_at\", \"solution_provider_id\" = EXCLUDED.\"solution_provider_id\"","parameters":["0014004562-000074-6a173",4,"635087",10972,10,"{\"version\":3,\"type\":\"vm\",\"name\":\"dl_c9ptcij4x8\",\"projectName\":\"vm/dl_c9ptcij4x8\"}","8b935ee693f71ea5fbefab6ca19288f3",0,"Deleted","1724902038",0],"driverError":{"length":221,"name":"error","severity":"ERROR","code":"P0001","where":"PL/pgSQL function reflect_node_contract_changes() line 27 at RAISE","file":"pl_exec.c","line":"3909","routine":"exec_stmt_raise","stack":"error: failed reflecting node_contract updates could not serialize access due to concurrent update\n    at /squid/node_modules/pg/lib/client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)\n    at async InsertQueryBuilder.execute (/squid/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)\n    at async Store.upsert (/squid/node_modules/@subsquid/typeorm-store/lib/store.js:34:13)\n    at async nodeContractCanceled (/squid/lib/mappings/contracts.js:239:5)\n    at async /squid/lib/processor.js:138:13\n    at async TypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    at async TypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    at async Runner.process (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:117:17)"},"length":221,"severity":"ERROR","code":"P0001","where":"PL/pgSQL function reflect_node_contract_changes() line 27 at RAISE","file":"pl_exec.c","line":"3909","routine":"exec_stmt_raise","stack":"QueryFailedError: failed reflecting node_contract updates could not serialize access due to concurrent update\n    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InsertQueryBuilder.execute (/squid/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)\n    at async Store.upsert (/squid/node_modules/@subsquid/typeorm-store/lib/store.js:34:13)\n    at async nodeContractCanceled (/squid/lib/mappings/contracts.js:239:5)\n    at async /squid/lib/processor.js:138:13\n    at async TypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    at async TypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    at async Runner.process (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:117:17)"}}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

https://[dashboard.be.grid.tf](https://dashboard.be.grid.tf/)/
```
{"level":2,"time":1725078125098,"ns":"sqd:processor","msg":"14033895 / 14033895, rate: 0 blocks/sec, mapping: 1 blocks/sec, 11 items/sec, ingest: 79 blocks/sec, eta: 0s"}
{"level":2,"time":1725078130119,"ns":"sqd:processor","msg":"14033896 / 14033896, rate: 0 blocks/sec, mapping: 1 blocks/sec, 13 items/sec, ingest: 81 blocks/sec, eta: 0s"}
{"level":2,"time":1725078135075,"ns":"sqd:processor","msg":"14033897 / 14033897, rate: 0 blocks/sec, mapping: 1 blocks/sec, 13 items/sec, ingest: 79 blocks/sec, eta: 0s"}
{"level":2,"time":1725078140381,"ns":"sqd:processor","msg":"14033898 / 14033898, rate: 0 blocks/sec, mapping: 1 blocks/sec, 12 items/sec, ingest: 76 blocks/sec, eta: 0s"}
{"level":2,"time":1725078149895,"ns":"sqd:processor","msg":"14033899 / 14033899, rate: 0 blocks/sec, mapping: 1 blocks/sec, 15 items/sec, ingest: 51 blocks/sec, eta: 0s"}
{"level":2,"time":1725078155024,"ns":"sqd:processor","msg":"14033900 / 14033900, rate: 0 blocks/sec, mapping: 1 blocks/sec, 15 items/sec, ingest: 46 blocks/sec, eta: 0s"}
{"level":2,"time":1725078159888,"ns":"sqd:processor","msg":"14033901 / 14033901, rate: 0 blocks/sec, mapping: 2 blocks/sec, 15 items/sec, ingest: 40 blocks/sec, eta: 0s"}
{"level":2,"time":1725078229754,"ns":"sqd:processor","msg":"14033902 / 14033904, rate: 0 blocks/sec, mapping: 0 blocks/sec, 9 items/sec, ingest: 24 blocks/sec, eta: 14s"}
{"level":2,"time":1725078230352,"ns":"sqd:processor","msg":"14033903 / 14033912, rate: 0 blocks/sec, mapping: 0 blocks/sec, 9 items/sec, ingest: 23 blocks/sec, eta: 2m"}
{"level":2,"time":1725078230941,"ns":"sqd:processor","msg":"14033904 / 14033913, rate: 0 blocks/sec, mapping: 0 blocks/sec, 9 items/sec, ingest: 25 blocks/sec, eta: 2m"}
{"level":2,"time":1725078246397,"ns":"sqd:processor","msg":"14033912 / 14033914, rate: 0 blocks/sec, mapping: 0 blocks/sec, 9 items/sec, ingest: 56 blocks/sec, eta: 13s"}
{"level":2,"time":1725078259299,"ns":"sqd:processor","msg":"14033913 / 14033915, rate: 0 blocks/sec, mapping: 0 blocks/sec, 9 items/sec, ingest: 53 blocks/sec, eta: 13s"}
{"level":2,"time":1725078270849,"ns":"sqd:processor","msg":"14033914 / 14033917, rate: 0 blocks/sec, mapping: 0 blocks/sec, 10 items/sec, ingest: 78 blocks/sec, eta: 20s"}
{"level":2,"time":1725078280516,"ns":"sqd:processor","msg":"14033915 / 14033919, rate: 0 blocks/sec, mapping: 0 blocks/sec, 10 items/sec, ingest: 76 blocks/sec, eta: 26s"}
{"level":2,"time":1725078291325,"ns":"sqd:processor","msg":"14033917 / 14033921, rate: 0 blocks/sec, mapping: 0 blocks/sec, 10 items/sec, ingest: 88 blocks/sec, eta: 26s"}
{"level":2,"time":1725078292292,"ns":"sqd:processor","msg":"14033919 / 14033923, rate: 0 blocks/sec, mapping: 0 blocks/sec, 10 items/sec, ingest: 59 blocks/sec, eta: 26s"}
{"level":2,"time":1725078293118,"ns":"sqd:processor","msg":"14033921 / 14033923, rate: 0 blocks/sec, mapping: 0 blocks/sec, 11 items/sec, ingest: 84 blocks/sec, eta: 12s"}
{"level":2,"time":1725078294225,"ns":"sqd:processor","msg":"14033923 / 14033923, rate: 0 blocks/sec, mapping: 0 blocks/sec, 13 items/sec, ingest: 108 blocks/sec, eta: 0s"}
{"level":2,"time":1725078297646,"ns":"sqd:processor","msg":"14033924 / 14033924, rate: 0 blocks/sec, mapping: 1 blocks/sec, 15 items/sec, ingest: 139 blocks/sec, eta: 0s"}
{"level":2,"time":1725078302733,"ns":"sqd:processor","msg":"14033925 / 14033925, rate: 0 blocks/sec, mapping: 2 blocks/sec, 24 items/sec, ingest: 137 blocks/sec, eta: 0s"}
{"level":2,"time":1725078307837,"ns":"sqd:processor","msg":"14033926 / 14033926, rate: 0 blocks/sec, mapping: 2 blocks/sec, 27 items/sec, ingest: 99 blocks/sec, eta: 0s"}
{"level":2,"time":1725078317928,"ns":"sqd:processor","msg":"14033927 / 14033927, rate: 0 blocks/sec, mapping: 2 blocks/sec, 27 items/sec, ingest: 76 blocks/sec, eta: 0s"}
{"level":2,"time":1725078322943,"ns":"sqd:processor","msg":"14033928 / 14033928, rate: 0 blocks/sec, mapping: 3 blocks/sec, 21 items/sec, ingest: 59 blocks/sec, eta: 0s"}
{"level":2,"time":1725078328106,"ns":"sqd:processor","msg":"14033929 / 14033929, rate: 0 blocks/sec, mapping: 2 blocks/sec, 26 items/sec, ingest: 58 blocks/sec, eta: 0s"}
{"level":2,"time":1725078333048,"ns":"sqd:processor","msg":"14033930 / 14033930, rate: 0 blocks/sec, mapping: 2 blocks/sec, 25 items/sec, ingest: 57 blocks/sec, eta: 0s"}
{"level":2,"time":1725078343023,"ns":"sqd:processor","msg":"14033931 / 14033931, rate: 0 blocks/sec, mapping: 2 blocks/sec, 22 items/sec, ingest: 53 blocks/sec, eta: 0s"}
{"level":2,"time":1725078348164,"ns":"sqd:processor","msg":"14033932 / 14033932, rate: 0 blocks/sec, mapping: 2 blocks/sec, 25 items/sec, ingest: 57 blocks/sec, eta: 0s"}
{"level":5,"time":1725078368509,"ns":"sqd:processor","err":{"query":"INSERT INTO \"node_contract\"(\"id\", \"grid_version\", \"contract_id\", \"twin_id\", \"node_id\", \"deployment_data\", \"deployment_hash\", \"number_of_public_i_ps\", \"state\", \"created_at\", \"solution_provider_id\", \"resources_used_id\") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, DEFAULT) ON CONFLICT ( \"id\" ) DO UPDATE SET \"id\" = EXCLUDED.\"id\", \"grid_version\" = EXCLUDED.\"grid_version\", \"contract_id\" = EXCLUDED.\"contract_id\", \"twin_id\" = EXCLUDED.\"twin_id\", \"node_id\" = EXCLUDED.\"node_id\", \"deployment_data\" = EXCLUDED.\"deployment_data\", \"deployment_hash\" = EXCLUDED.\"deployment_hash\", \"number_of_public_i_ps\" = EXCLUDED.\"number_of_public_i_ps\", \"state\" = EXCLUDED.\"state\", \"created_at\" = EXCLUDED.\"created_at\", \"solution_provider_id\" = EXCLUDED.\"solution_provider_id\"","parameters":["0014033933-000242-d071b",4,"638332",10972,1754,"{\"version\":3,\"type\":\"vm\",\"name\":\"example_c11\",\"projectName\":\"vm/group_c\"}","5fdcf2571a269cefd48a707552afc56a",0,"Created","1725078336",0],"driverError":{"length":214,"name":"error","severity":"ERROR","code":"P0001","where":"PL/pgSQL function reflect_node_contract_changes() line 42 at RAISE","file":"pl_exec.c","line":"3909","routine":"exec_stmt_raise","stack":"error: failed calc node_contracts_count could not serialize access due to concurrent update\n    at /squid/node_modules/pg/lib/client.js:526:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)\n    at async InsertQueryBuilder.execute (/squid/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)\n    at async Store.upsert (/squid/node_modules/@subsquid/typeorm-store/lib/store.js:34:13)\n    at async contractCreated (/squid/lib/mappings/contracts.js:106:9)\n    at async /squid/lib/processor.js:138:13\n    at async TypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    at async TypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    at async Runner.process (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:117:17)"},"length":214,"severity":"ERROR","code":"P0001","where":"PL/pgSQL function reflect_node_contract_changes() line 42 at RAISE","file":"pl_exec.c","line":"3909","routine":"exec_stmt_raise","stack":"QueryFailedError: failed calc node_contracts_count could not serialize access due to concurrent update\n    at PostgresQueryRunner.query (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async InsertQueryBuilder.execute (/squid/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)\n    at async Store.upsert (/squid/node_modules/@subsquid/typeorm-store/lib/store.js:34:13)\n    at async contractCreated (/squid/lib/mappings/contracts.js:106:9)\n    at async /squid/lib/processor.js:138:13\n    at async TypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)\n    at async TypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)\n    at async Runner.process (/squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:117:17)"}}
error Command failed with exit code 1.
```

..

**Comment by hossnys** [comment]
- it was related to gridproxy issue which is fixed in this version update here https://github.com/threefoldtech/tf_operations/issues/2824#
