### ISSUE TITLE
Connection price contains null values

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#36]
Error on devnet

**Comment by DylanVerstraete** [comment]
```
  file: 'tablecmds.c',
  line: '5244',
  routine: 'ATRewriteTable'
}
Migration "ddao1655110017248" failed, error: column "connection_price" contains null values
query: ROLLBACK
QueryFailedError: column "connection_price" contains null values
    at QueryFailedError.TypeORMError [as constructor] (/squid/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/squid/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/squid/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/squid/node_modules/tslib/tslib.js:124:57)
    at rejected (/squid/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'ALTER TABLE "node" ADD "connection_price" integer NOT NULL',
  parameters: undefined,
  driverError: error: column "connection_price" contains null values
      at Parser.parseErrorMessage (/squid/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/squid/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/squid/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/squid/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:526:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 141,
    severity: 'ERROR',
    code: '23502',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'node',
    column: 'connection_price',
    dataType: undefined,
    constraint: undefined,
    file: 'tablecmds.c',
    line: '5244',
    routine: 'ATRewriteTable'
  },
  length: 141,

```
