### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#37]
```
Migration "graceperiod1653490002499" failed, error: cannot drop column state of table node_contract because other objects depend on it
query: ROLLBACK
QueryFailedError: cannot drop column state of table node_contract because other objects depend on it
    at QueryFailedError.TypeORMError [as constructor] (/squid/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/squid/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/squid/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/squid/node_modules/tslib/tslib.js:124:57)
    at rejected (/squid/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'ALTER TABLE "node_contract" DROP COLUMN "state"',
  parameters: undefined,
  driverError: error: cannot drop column state of table node_contract because other objects depend on it
      at Parser.parseErrorMessage (/squid/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/squid/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/squid/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/squid/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:526:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 285,
    severity: 'ERROR',
    code: '2BP01',
    detail: 'view nodes_resources_view depends on column state of table node_contract',
    hint: 'Use DROP ... CASCADE to drop the dependent objects too.',
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'dependency.c',
    line: '1194',
    routine: 'reportDependentObjects'
```

**Comment by DylanVerstraete** [comment]
fixed here https://github.com/threefoldtech/tfchain_graphql/commit/3b3022664f37c87e09c53645b9fef74e66bbc883
