### ISSUE TITLE
Grapqhl crash on devnet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#50]
```
> graphql_tfgrid@2.3.0 process
> node db/init.js && node init-countries.js && node -r dotenv/config lib/processor.js

query: SELECT * FROM current_schema()
query: SHOW server_version;
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
No migrations are pending
error: duplicate key value violates unique constraint "PK_bf6e37c231c4f4ea56dcd887269"
    at Parser.parseErrorMessage (/squid/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/squid/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/squid/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/squid/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 222,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(1) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'country',
  column: undefined,
  dataType: undefined,
  constraint: 'PK_bf6e37c231c4f4ea56dcd887269',
  file: 'nbtinsert.c',
  line: '563',
  routine: '_bt_check_unique'
}
Prometheus metrics are served at port 44233
/squid/node_modules/typeorm/error/TypeORMError.js:9
        var _this = _super.call(this, message) || this;
                           ^

QueryFailedError: invalid byte sequence for encoding "UTF8": 0x00
    at QueryFailedError.TypeORMError [as constructor] (/squid/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/squid/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/squid/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/squid/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/squid/node_modules/tslib/tslib.js:124:57)
    at rejected (/squid/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'SELECT "PublicIp"."id" AS "PublicIp_id", "PublicIp"."gateway" AS "PublicIp_gateway", "PublicIp"."ip" AS "PublicIp_ip", "PublicIp"."contract_id" AS "PublicIp_contract_id", "PublicIp"."farm_id" AS "PublicIp_farm_id" FROM "public_ip" "PublicIp" WHERE "PublicIp"."ip" = $1 LIMIT 1',
  parameters: [ '\x00\x00' ],
  driverError: error: invalid byte sequence for encoding "UTF8": 0x00
      at Parser.parseErrorMessage (/squid/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/squid/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/squid/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/squid/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:526:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 115,
    severity: 'ERROR',
    code: '22021',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'wchar.c',
    line: '2061',
    routine: 'report_invalid_encoding'
  },
  length: 115,
  severity: 'ERROR',
  code: '22021',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'wchar.c',
  line: '2061',
  routine: 'report_invalid_encoding'
}
npm notice 
npm notice New minor version of npm available! 8.5.0 -> 8.16.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.16.0>
npm notice Run `npm install -g npm@8.16.0` to update!
npm notice 

```

**Comment by DylanVerstraete** [comment]
fixed in `2.4.4`
