### ISSUE TITLE
Processor crash devnet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#51]
```
}
Prometheus metrics are served at port 44233
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(this.isV19)

    at SmartContractModuleNodeContractCanceledEvent.get asV19 [as asV19] (/squid/lib/types/events.js:312:30)
    at nodeContractCanceled (/squid/lib/mappings/contracts.js:168:88)
    at /squid/lib/processor.js:46:115
    at /squid/node_modules/@subsquid/substrate-processor/lib/processor.js:190:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /squid/node_modules/@subsquid/substrate-processor/lib/db.js:69:13 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.17.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.17.0>
npm notice Run `npm install -g npm@8.17.0` to update!
npm notice 


```

**Comment by DylanVerstraete** [comment]
fixed in https://github.com/threefoldtech/tfchain_graphql/commit/e39ace0b412a433fbd238502db9e1cd048af8b58
